Homework
Pekhov/qna pull request #1
Opened 2019-03-01 12:48 UTC by Pekhov

2019-03-01 15:40 UTC, vkurennov requested changes

2019-03-01 15:40 UTC, vkurennov commented on app/models/question.rb
> +  has_many :answers
тут нужна опция, при которой удалени вопроса также удалит и связанные ответы. и не забудь протестировать эту опцию,  shoulda-matchers это умеет

2019-03-01 15:40 UTC, vkurennov commented on app/models/question.rb
> +
пустая строка в конце классов, методов, блоков не ставится

2019-03-02 08:29 UTC, Pekhov commented on app/models/question.rb
> +  has_many :answers
Исправил

2019-03-02 08:29 UTC, Pekhov commented on app/models/question.rb
> +
Исправил

2019-03-02 09:32 UTC, vkurennov approved these changes

2019-03-02 09:37 UTC, merged